### ISSUE TITLE
程序运行时出错

### ISSUE THREAD

**Issue by hanleirx** [coderoom1401/ReactNative_WeatherProj#1]
你好，我运行这个代码会报错：06-28 21:11:42.495 4862-4885/com.weatherproj E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                               Process: com.weatherproj, PID: 4862
                                                               java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                   at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                   at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                   at java.lang.Thread.run(Thread.java:841)
                                                                Caused by: java.lang.IllegalAccessError: tried to access method android.support.v4.net.ConnectivityManagerCompat.<init>:(Lcom/facebook/react/bridge/ReactApplicationContext;)V from class com.facebook.react.modules.netinfo.NetInfoModule
                                                                   at com.facebook.react.modules.netinfo.NetInfoModule.<init>(NetInfoModule.java:55)
                                                                   at com.facebook.react.shell.MainReactPackage.createNativeModules(MainReactPackage.java:67)
                                                                   at com.facebook.react.ReactInstanceManagerImpl.processPackage(ReactInstanceManagerImpl.java:793)
                                                                   at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:730)
                                                                   at com.facebook.react.ReactInstanceManagerImpl.access$600(ReactInstanceManagerImpl.java:91)
                                                                   at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:184)
                                                                   at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:169)
                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                   at java.lang.Thread.run(Thread.java:841) 
为什么啊 ，求解答

**Comment by liang3472** [comment]
你的reactnative开发环搭好了？这是[reactnative中文网](http://reactnative.cn/docs/0.27/getting-started.html#content)，请按步骤配置环境，希望能帮到你
